root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/chess ."

bin = "tmp/chess"

include_ext = ["go"]

exclude_dir = ["build", "frontend"]

delay = 1000

stop_on_error = true

log = "air_errors.log"

[log]
time = true

